[package]
name = "rust_yew"
version = "0.1.0"
authors = ["lhjok <lhjok@live.cn>"]
description = "Rust Yew"
edition = "2021"
license = "MIT"

[dependencies]
wasm-bindgen = "0.2.82"
yew = "0.19"
yew-router = "0.16"

[dev-dependencies]
wasm-bindgen-test = "0.3.32"